apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: hello-nginx-nonprod
  labels:
    app: hello-nginx
    env: nonprod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
        env: nonprod
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
